### ISSUE TITLE
[Feature] `mapping.close`

### ISSUE THREAD

**Issue by eddiebergman** [nvim-neotest/neotest#179]
It'd be nice to have a mapping option for closing neotest, i.e.
```lua
mappings = {
  ...,
  close = "q"
}
```

This is line with a lot of other plugins that have a sidebar.

Big fan, keep it up Ronan :)

**Comment by rcarriga** [comment]
Well hello there! 

I've actually avoided these kind of mappings because they can cause issues (e.g. https://github.com/nvim-neotest/neotest/issues/135) and it is easy for users to add them themselves. The summary mappings that do exist are not able to be implemented by users as they would require extra information that isn't available such as what position a line corresponds to (though I've had thoughts to expose that as well :sweat_smile:)

I have this in my config:
```lua
  local group = vim.api.nvim_create_augroup("NeotestConfig", {})
  for _, ft in ipairs({ "output", "attach", "summary" }) do
    vim.api.nvim_create_autocmd("FileType", {
      pattern = "neotest-" .. ft,
      group = group,
      callback = function(opts)
        vim.keymap.set("n", "q", function()
          pcall(vim.api.nvim_win_close, 0, true)
        end, {
          buffer = opts.buf,
        })
      end,
    })
  end
```

**Comment by eddiebergman** [comment]
I'll add this little gem in then, thank you :)

On the convenience side, a nice halfway point would be that `close = nil` is the default so it's just opt-in and easily revertible.

Keep up the good stuff!
