### ISSUE TITLE
API to merge multiple positions into a single test command?

### ISSUE THREAD

**Issue by mrcjkb** [nvim-neotest/neotest#212]
If multiple positions are found (e.g. when calling `neotest.run.run(vim.api.nvim_buf_get_name(0))`, the adapter's `build_spec` will be called once for each position, resulting in separate processes for each one.

This can be an issue for Cabal (see https://github.com/mrcjkb/neotest-haskell/issues/45).

Hspec has the ability to filter for multiple positions at once, so multiple test positions could be run at the same time.

Is there a way to implement this in an adapter with the current Neotest API? If not, would it be feasible to implement such an API?

A (less efficient, but probably easier to implement) alternative would be to prevent multiple processes from being run concurrently.

**Comment by rcarriga** [comment]
Neotest already allows adapters to specify single commands for groups of tests, the reason multiple commands are being run is because the adapter doesn't support running any position type other than "test" types https://github.com/mrcjkb/neotest-haskell/blob/master/lua/neotest-haskell/init.lua#L46-L48. Neotest will automatically try to break up groups of tests https://github.com/rcarriga/neotest/blob/0d17889ce740c83c18577487498a1a8fea144b0b/lua/neotest/client/runner.lua#L77-L82

**Comment by mrcjkb** [comment]
That's great. Thanks for the info 🙏
