### ISSUE TITLE
Configure status icons

### ISSUE THREAD

**Issue by augustocdias** [nvim-neotest/neotest#79]
How to configure the status in the signcolumn? 

The `running` status is broken on my setup and I can't replace it with anything. Which font has this symbol? I'm using `Fira Code Nerdfont`

**Comment by rcarriga** [comment]
I'm using https://github.com/microsoft/vscode-codicons for my icons.

You can configure them by passing an `icons` table to `setup`, see `:h neotest.setup()` for the default values.

**Comment by rouge8** [comment]
Which codicons are you using for `running` and `skipped`? https://microsoft.github.io/vscode-codicons/dist/codicon.html

**Comment by page-down** [comment]
@rouge8
Since you asked about this
https://github.com/kovidgoyal/kitty/issues/5332

I decided to reply to your question in this issue.
Based on the information you provided, the `running` icon `U+1F5D8`  should be corrected to `U+EA77` (sync) to use vscode-codicons.
Under macOS, there is no default font that displays the default running icon `U+1F5D8`.

The `skipped` icon is `U+FC38`, which uses the Nerd Fonts icon.
However, this range has **exceeded the Private Use Area**, which causes many problems and icons in this range should not be used.
Nerd Fonts 3.0 will remove the use of these inappropriate ranges.
https://github.com/ryanoasis/nerd-fonts/discussions/716

So, I recommend fixing it in the default configuration and try to use the **same icon font** by default.

**Comment by rcarriga** [comment]
> So, I recommend fixing it in the default configuration and try to use the same icon font by default.

I'd be happy to do this. Would love some suggestions, I just threw in the first ones that made sense to me when I decided on the originals, there wasn't much thought to it :sweat_smile:

**Comment by augustocdias** [comment]
How about any of those?
* `U+FCC1` ﳁ
* `U+FCC2` ﳂ
* `U+F7B0` 
* `U+F192` 
* `U+F1CE` 

**Comment by rouge8** [comment]
I think `U+FCC1` and `U+FCC2` exceed the unicode private use area since it looks like they have Arabic/Persian/Urdu characters.

**Comment by rcarriga** [comment]
Ive updated the defaults to use all codicons icons. Nerd fonts is probably more popular but the non-PUA usage is a pain and codicons provide a consistent appearance
